### ISSUE TITLE
Error installing on Odoo 9.0c

### ISSUE THREAD

**Issue by tzbmike** [marcok/odoo_modules#13]
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 646, in _handle_exception
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 683, in dispatch
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 319, in _call_function
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 312, in checked_call
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 962, in __call__
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\http.py", line 512, in response_wrap
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\web\controllers\main.py", line 901, in call_button
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\web\controllers\main.py", line 889, in _call_kw
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\base\module\module.py", line 533, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\modules\loading.py", line 338, in load_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\modules\loading.py", line 237, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\modules\loading.py", line 98, in _load_data
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 851, in convert_file
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 938, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 801, in parse
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 804, in parse
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 503, in _tag_menuitem
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 782, in id_get
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\convert.py", line 793, in model_id_get
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\base\ir\ir_model.py", line 983, in xmlid_to_res_model_res_id
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\api.py", line 250, in wrapper
  File "<string>", line 2, in xmlid_lookup
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\.\openerp\tools\cache.py", line 85, in lookup
  File "C:\Program Files (x86)\Odoo 9.0-20160624\server\openerp\addons\base\ir\ir_model.py", line 973, in xmlid_lookup
ParseError: "External ID not found in the system: hr.menu_hr_reporting" while parsing file:///C:/Users/mike/AppData/Local/OpenERP%20S.A/Odoo/addons/9.0/hr_employee_time_clock/report/report_attendance_analysis_view.xml:40, near
<menuitem action="action_hr_attendance_analysis_report" id="menu_hr_attendance_analysis_report" parent="hr.menu_hr_reporting" groups="base.group_hr_user" sequence="3"/>

**Comment by tzbmike** [comment]
<menuitem action="action_hr_attendance_analysis_report" id="menu_hr_attendance_analysis_report" parent="hr.menu_hr_reporting" groups="base.group_hr_user" sequence="3"/>

**Comment by rokealva83** [comment]
If you use the 8th version, then install:
https://github.com/marcok/odoo_modules/tree/8.0
If you use the 9th version, then install:
https://github.com/marcok/odoo_modules/tree/9.0
