### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by sluger25** [marcok/odoo_modules#14]
I installed your Employee time clock module on Oddo 10 Community Edition. Unfortunately, it does not work correctly. When I open „My Timesheet” or „Submit for approval” Odoo shows server Error below:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3020, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5211, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1022, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python2.7/site-packages/odoo/addons_SK/hr_employee_time_clock/models/hr_timesheet_dh.py", line 186, in _get_analysis
    output.append('<td>' + td + '</td>')
TypeError: cannot concatenate 'str' and 'NoneType' objects

What should I do to run the module?

**Comment by rokealva83** [comment]
Good day. I apologize for the long silence. I need additional information, because testing in a new database does not repeat such an error.

**Comment by sluger25** [comment]
Hi,
What additional information do you need?
I use Odoo 10.0-20180226 Community Edition.

**Comment by rokealva83** [comment]
I installed the module with one click on the new database 2 hours ago. There were no problems. 
All menus open normally.
Did you install the module on a clean database or did it already contain data?
Do you have other modules not from assembly?
If so, which ones?
